#include<iostream>
using  namespace std;

// int main(){
//     // int  x=100;
//     // int &y=x;    // & is thwe  referance variable 
    
//     // cout<<"the value of x is"<<y;
    
//     //************************* TYPECASTING*******************

//     // FOR CONVERTING DATA TYPES

//         float  a=10.5;
//         cout<<"the int value of a is"<<(int)a;

// return 0;
// }

int main(){

    int x=100;
    int &y=x;
    cout<<"the value of x  is "<<y<<endl;
    return 0;
}